# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when 
# increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [7]:
def func(vec, n, inc=True):
    if inc:
        m = np.matrix([i**j for i in vec for j in range(n)]).reshape(vec.size, n)
    else:
        m = np.matrix([i**(n-j-1) for i in vec for j in range(n)]).reshape(vec.size, n)
    return m

In [8]:
vec = np.array([1,3,5,7,9])
n = 5
print(func(vec,n,False))

[[   1    1    1    1    1]
 [  81   27    9    3    1]
 [ 625  125   25    5    1]
 [2401  343   49    7    1]
 [6561  729   81    9    1]]


# Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [31]:
def func2(arr, k):
    flag = 1
    res = np.convolve(arr, np.ones(k), mode = "valid")/k
    for i in res:
        print("y{0} = {1:.3f}".format(flag, i))
        flag = flag+1

In [32]:
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
func2(arr, k)

y1 = 5.000
y2 = 4.667
y3 = 5.667
y4 = 6.667
y5 = 9.667
y6 = 28.667
y7 = 49.333
y8 = 72.667
y9 = 84.000
y10 = 93.333
y11 = 116.333
